/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import * as zod from 'zod';


/**
 * Returns server health status
 * @summary Health check
 */
export const HealthCheckResponse = zod.object({
  "status": zod.string()
})


/**
 * @summary Get a coarse-area leaderboard
 */
export const getAreaLeaderboardQueryAreaKeyMin = 2;
export const getAreaLeaderboardQueryAreaKeyMax = 120;



export const GetAreaLeaderboardQueryParams = zod.object({
  "areaKey": zod.coerce.string().min(getAreaLeaderboardQueryAreaKeyMin).max(getAreaLeaderboardQueryAreaKeyMax)
})

export const GetAreaLeaderboardResponse = zod.object({
  "areaLabel": zod.string(),
  "entries": zod.array(zod.object({
  "nickname": zod.string(),
  "focusMinutes": zod.number().int(),
  "stillnessMinutes": zod.number().int(),
  "totalMinutes": zod.number().int(),
  "updatedAt": zod.coerce.date()
}))
})


/**
 * @summary Sync this installation's measured activity totals
 */
export const syncAreaLeaderboardBodyInstallationIdMin = 8;
export const syncAreaLeaderboardBodyInstallationIdMax = 128;

export const syncAreaLeaderboardBodyNicknameMin = 2;
export const syncAreaLeaderboardBodyNicknameMax = 40;

export const syncAreaLeaderboardBodyAreaKeyMin = 2;
export const syncAreaLeaderboardBodyAreaKeyMax = 120;

export const syncAreaLeaderboardBodyAreaLabelMin = 2;
export const syncAreaLeaderboardBodyAreaLabelMax = 120;

export const syncAreaLeaderboardBodyFocusMinutesMin = 0;
export const syncAreaLeaderboardBodyFocusMinutesMax = 100000;

export const syncAreaLeaderboardBodyStillnessMinutesMin = 0;
export const syncAreaLeaderboardBodyStillnessMinutesMax = 100000;



export const SyncAreaLeaderboardBody = zod.object({
  "installationId": zod.string().min(syncAreaLeaderboardBodyInstallationIdMin).max(syncAreaLeaderboardBodyInstallationIdMax),
  "nickname": zod.string().min(syncAreaLeaderboardBodyNicknameMin).max(syncAreaLeaderboardBodyNicknameMax),
  "areaKey": zod.string().min(syncAreaLeaderboardBodyAreaKeyMin).max(syncAreaLeaderboardBodyAreaKeyMax),
  "areaLabel": zod.string().min(syncAreaLeaderboardBodyAreaLabelMin).max(syncAreaLeaderboardBodyAreaLabelMax),
  "focusMinutes": zod.number().int().min(syncAreaLeaderboardBodyFocusMinutesMin).max(syncAreaLeaderboardBodyFocusMinutesMax),
  "stillnessMinutes": zod.number().int().min(syncAreaLeaderboardBodyStillnessMinutesMin).max(syncAreaLeaderboardBodyStillnessMinutesMax)
})

export const SyncAreaLeaderboardResponse = zod.object({
  "nickname": zod.string(),
  "focusMinutes": zod.number().int(),
  "stillnessMinutes": zod.number().int(),
  "totalMinutes": zod.number().int(),
  "updatedAt": zod.coerce.date()
})


/**
 * @summary Explain a study question using the supplied subject and materials
 */
export const explainTutorQuestionBodySubjectMax = 80;

export const explainTutorQuestionBodyMaterialsMax = 12000;

export const explainTutorQuestionBodyImageDataUrlMax = 5000000;

export const explainTutorQuestionBodyQuestionMax = 4000;



export const ExplainTutorQuestionBody = zod.object({
  "subject": zod.string().min(1).max(explainTutorQuestionBodySubjectMax),
  "materials": zod.string().max(explainTutorQuestionBodyMaterialsMax).optional(),
  "imageDataUrl": zod.string().max(explainTutorQuestionBodyImageDataUrlMax).optional().describe('Optional camera photo encoded as a data URL for visual study material.'),
  "question": zod.string().min(1).max(explainTutorQuestionBodyQuestionMax)
})

export const ExplainTutorQuestionResponse = zod.object({
  "explanation": zod.string(),
  "keyIdeas": zod.array(zod.string()),
  "followUp": zod.string()
})


/**
 * @summary Generate a playful roast for a focus interruption
 */
export const generateRoastBodyElapsedMinutesMin = 0;
export const generateRoastBodyElapsedMinutesMax = 1440;

export const generateRoastBodyOverrideCountMin = 0;
export const generateRoastBodyOverrideCountMax = 1000;



export const GenerateRoastBody = zod.object({
  "style": zod.enum(['classic', 'bold', 'dry', 'chaos', 'margin-notes']),
  "mode": zod.enum(['override', 'app-switch', 'end-session']),
  "elapsedMinutes": zod.number().int().min(generateRoastBodyElapsedMinutesMin).max(generateRoastBodyElapsedMinutesMax),
  "overrideCount": zod.number().int().min(generateRoastBodyOverrideCountMin).max(generateRoastBodyOverrideCountMax)
})

export const GenerateRoastResponse = zod.object({
  "roast": zod.string()
})


/**
 * @summary Restore the signed-in user's latest practice snapshot
 */
export const getPracticeResponseRevisionMin = 0;

export const getPracticeResponseSnapshotOneFocusAppsItemIdMax = 200;

export const getPracticeResponseSnapshotOneFocusAppsItemNameMax = 100;

export const getPracticeResponseSnapshotOneFocusAppsItemCategoryMax = 100;

export const getPracticeResponseSnapshotOneFocusAppsMax = 100;

export const getPracticeResponseSnapshotOneFocusSessionsItemIdMax = 200;

export const getPracticeResponseSnapshotOneFocusSessionsItemCompletedAtMax = 40;

export const getPracticeResponseSnapshotOneFocusSessionsItemDurationMinutesMax = 1440;

export const getPracticeResponseSnapshotOneFocusSessionsItemReflectionNoteMax = 2000;

export const getPracticeResponseSnapshotOneFocusSessionsMax = 20000;

export const getPracticeResponseSnapshotOneFocusOverrideEventsItemMax = 40;

export const getPracticeResponseSnapshotOneFocusOverrideEventsMax = 50000;

export const getPracticeResponseSnapshotOneFocusPendingReflectionIdOneMax = 200;

export const getPracticeResponseSnapshotOneFocusStasisTokensMin = 0;
export const getPracticeResponseSnapshotOneFocusStasisTokensMax = 100000;

export const getPracticeResponseSnapshotOneFocusProtectedDateKeysItemMax = 20;

export const getPracticeResponseSnapshotOneFocusProtectedDateKeysMax = 10000;

export const getPracticeResponseSnapshotOneRewardsLeavesMin = 0;
export const getPracticeResponseSnapshotOneRewardsLeavesMax = 10000000;

export const getPracticeResponseSnapshotOneRewardsMindfulMinutesMin = 0;
export const getPracticeResponseSnapshotOneRewardsMindfulMinutesMax = 10000000;

export const getPracticeResponseSnapshotOneRewardsUnlockedRewardsItemMax = 200;

export const getPracticeResponseSnapshotOneRewardsUnlockedRewardsMax = 1000;

export const getPracticeResponseSnapshotOneRewardsStillnessEventsItemMax = 40;

export const getPracticeResponseSnapshotOneRewardsStillnessEventsMax = 50000;

export const getPracticeResponseSnapshotOneRewardsOwnedCollectiblesMax = 4;

export const getPracticeResponseSnapshotOneRewardsRewardClaimKeysItemMax = 100;

export const getPracticeResponseSnapshotOneRewardsRewardClaimKeysMax = 10000;



export const GetPracticeResponse = zod.object({
  "revision": zod.number().int().min(getPracticeResponseRevisionMin),
  "snapshot": zod.union([zod.object({
  "version": zod.literal(1),
  "focus": zod.object({
  "apps": zod.array(zod.object({
  "id": zod.string().min(1).max(getPracticeResponseSnapshotOneFocusAppsItemIdMax),
  "name": zod.string().min(1).max(getPracticeResponseSnapshotOneFocusAppsItemNameMax),
  "category": zod.string().min(1).max(getPracticeResponseSnapshotOneFocusAppsItemCategoryMax),
  "active": zod.boolean()
})).max(getPracticeResponseSnapshotOneFocusAppsMax),
  "sessions": zod.array(zod.object({
  "id": zod.string().min(1).max(getPracticeResponseSnapshotOneFocusSessionsItemIdMax),
  "completedAt": zod.string().min(1).max(getPracticeResponseSnapshotOneFocusSessionsItemCompletedAtMax),
  "durationMinutes": zod.number().int().min(1).max(getPracticeResponseSnapshotOneFocusSessionsItemDurationMinutesMax),
  "reflection": zod.object({
  "feeling": zod.enum(['clear', 'okay', 'scattered']),
  "note": zod.string().max(getPracticeResponseSnapshotOneFocusSessionsItemReflectionNoteMax).optional()
}).optional()
})).max(getPracticeResponseSnapshotOneFocusSessionsMax),
  "overrideEvents": zod.array(zod.string().min(1).max(getPracticeResponseSnapshotOneFocusOverrideEventsItemMax)).max(getPracticeResponseSnapshotOneFocusOverrideEventsMax),
  "pendingReflectionId": zod.union([zod.string().min(1).max(getPracticeResponseSnapshotOneFocusPendingReflectionIdOneMax),zod.null()]),
  "stasisTokens": zod.number().int().min(getPracticeResponseSnapshotOneFocusStasisTokensMin).max(getPracticeResponseSnapshotOneFocusStasisTokensMax),
  "protectedDateKeys": zod.array(zod.string().min(1).max(getPracticeResponseSnapshotOneFocusProtectedDateKeysItemMax)).max(getPracticeResponseSnapshotOneFocusProtectedDateKeysMax)
}),
  "rewards": zod.object({
  "leaves": zod.number().int().min(getPracticeResponseSnapshotOneRewardsLeavesMin).max(getPracticeResponseSnapshotOneRewardsLeavesMax),
  "mindfulMinutes": zod.number().int().min(getPracticeResponseSnapshotOneRewardsMindfulMinutesMin).max(getPracticeResponseSnapshotOneRewardsMindfulMinutesMax),
  "unlockedRewards": zod.array(zod.string().min(1).max(getPracticeResponseSnapshotOneRewardsUnlockedRewardsItemMax)).max(getPracticeResponseSnapshotOneRewardsUnlockedRewardsMax),
  "equipped": zod.object({
  "breath": zod.enum(['classic', 'moonlight', 'starlight', 'sunrise', 'aurora', 'paperfold']),
  "roast": zod.enum(['classic', 'bold', 'dry', 'chaos', 'margin-notes'])
}),
  "stillnessEvents": zod.array(zod.string().min(1).max(getPracticeResponseSnapshotOneRewardsStillnessEventsItemMax)).max(getPracticeResponseSnapshotOneRewardsStillnessEventsMax),
  "ownedCollectibles": zod.array(zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page'])).max(getPracticeResponseSnapshotOneRewardsOwnedCollectiblesMax),
  "selectedCollectible": zod.union([zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page']),zod.null()]),
  "soundscape": zod.enum(['none', 'rainy-library', 'quiet-spacecraft', 'turning-pages', 'greenhouse-rain', 'misty-window', 'sunday-vinyl', 'ocean-desk', 'library-lamp']),
  "rewardClaimKeys": zod.array(zod.string().min(1).max(getPracticeResponseSnapshotOneRewardsRewardClaimKeysItemMax)).max(getPracticeResponseSnapshotOneRewardsRewardClaimKeysMax).optional()
})
}),zod.null()]),
  "updatedAt": zod.union([zod.coerce.date(),zod.null()])
})


/**
 * @summary Save a practice snapshot when its expected revision is current
 */
export const savePracticeBodyExpectedRevisionMin = 0;

export const savePracticeBodySnapshotFocusAppsItemIdMax = 200;

export const savePracticeBodySnapshotFocusAppsItemNameMax = 100;

export const savePracticeBodySnapshotFocusAppsItemCategoryMax = 100;

export const savePracticeBodySnapshotFocusAppsMax = 100;

export const savePracticeBodySnapshotFocusSessionsItemIdMax = 200;

export const savePracticeBodySnapshotFocusSessionsItemCompletedAtMax = 40;

export const savePracticeBodySnapshotFocusSessionsItemDurationMinutesMax = 1440;

export const savePracticeBodySnapshotFocusSessionsItemReflectionNoteMax = 2000;

export const savePracticeBodySnapshotFocusSessionsMax = 20000;

export const savePracticeBodySnapshotFocusOverrideEventsItemMax = 40;

export const savePracticeBodySnapshotFocusOverrideEventsMax = 50000;

export const savePracticeBodySnapshotFocusPendingReflectionIdOneMax = 200;

export const savePracticeBodySnapshotFocusStasisTokensMin = 0;
export const savePracticeBodySnapshotFocusStasisTokensMax = 100000;

export const savePracticeBodySnapshotFocusProtectedDateKeysItemMax = 20;

export const savePracticeBodySnapshotFocusProtectedDateKeysMax = 10000;

export const savePracticeBodySnapshotRewardsLeavesMin = 0;
export const savePracticeBodySnapshotRewardsLeavesMax = 10000000;

export const savePracticeBodySnapshotRewardsMindfulMinutesMin = 0;
export const savePracticeBodySnapshotRewardsMindfulMinutesMax = 10000000;

export const savePracticeBodySnapshotRewardsUnlockedRewardsItemMax = 200;

export const savePracticeBodySnapshotRewardsUnlockedRewardsMax = 1000;

export const savePracticeBodySnapshotRewardsStillnessEventsItemMax = 40;

export const savePracticeBodySnapshotRewardsStillnessEventsMax = 50000;

export const savePracticeBodySnapshotRewardsOwnedCollectiblesMax = 4;

export const savePracticeBodySnapshotRewardsRewardClaimKeysItemMax = 100;

export const savePracticeBodySnapshotRewardsRewardClaimKeysMax = 10000;



export const SavePracticeBody = zod.object({
  "expectedRevision": zod.number().int().min(savePracticeBodyExpectedRevisionMin),
  "snapshot": zod.object({
  "version": zod.literal(1),
  "focus": zod.object({
  "apps": zod.array(zod.object({
  "id": zod.string().min(1).max(savePracticeBodySnapshotFocusAppsItemIdMax),
  "name": zod.string().min(1).max(savePracticeBodySnapshotFocusAppsItemNameMax),
  "category": zod.string().min(1).max(savePracticeBodySnapshotFocusAppsItemCategoryMax),
  "active": zod.boolean()
})).max(savePracticeBodySnapshotFocusAppsMax),
  "sessions": zod.array(zod.object({
  "id": zod.string().min(1).max(savePracticeBodySnapshotFocusSessionsItemIdMax),
  "completedAt": zod.string().min(1).max(savePracticeBodySnapshotFocusSessionsItemCompletedAtMax),
  "durationMinutes": zod.number().int().min(1).max(savePracticeBodySnapshotFocusSessionsItemDurationMinutesMax),
  "reflection": zod.object({
  "feeling": zod.enum(['clear', 'okay', 'scattered']),
  "note": zod.string().max(savePracticeBodySnapshotFocusSessionsItemReflectionNoteMax).optional()
}).optional()
})).max(savePracticeBodySnapshotFocusSessionsMax),
  "overrideEvents": zod.array(zod.string().min(1).max(savePracticeBodySnapshotFocusOverrideEventsItemMax)).max(savePracticeBodySnapshotFocusOverrideEventsMax),
  "pendingReflectionId": zod.union([zod.string().min(1).max(savePracticeBodySnapshotFocusPendingReflectionIdOneMax),zod.null()]),
  "stasisTokens": zod.number().int().min(savePracticeBodySnapshotFocusStasisTokensMin).max(savePracticeBodySnapshotFocusStasisTokensMax),
  "protectedDateKeys": zod.array(zod.string().min(1).max(savePracticeBodySnapshotFocusProtectedDateKeysItemMax)).max(savePracticeBodySnapshotFocusProtectedDateKeysMax)
}),
  "rewards": zod.object({
  "leaves": zod.number().int().min(savePracticeBodySnapshotRewardsLeavesMin).max(savePracticeBodySnapshotRewardsLeavesMax),
  "mindfulMinutes": zod.number().int().min(savePracticeBodySnapshotRewardsMindfulMinutesMin).max(savePracticeBodySnapshotRewardsMindfulMinutesMax),
  "unlockedRewards": zod.array(zod.string().min(1).max(savePracticeBodySnapshotRewardsUnlockedRewardsItemMax)).max(savePracticeBodySnapshotRewardsUnlockedRewardsMax),
  "equipped": zod.object({
  "breath": zod.enum(['classic', 'moonlight', 'starlight', 'sunrise', 'aurora', 'paperfold']),
  "roast": zod.enum(['classic', 'bold', 'dry', 'chaos', 'margin-notes'])
}),
  "stillnessEvents": zod.array(zod.string().min(1).max(savePracticeBodySnapshotRewardsStillnessEventsItemMax)).max(savePracticeBodySnapshotRewardsStillnessEventsMax),
  "ownedCollectibles": zod.array(zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page'])).max(savePracticeBodySnapshotRewardsOwnedCollectiblesMax),
  "selectedCollectible": zod.union([zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page']),zod.null()]),
  "soundscape": zod.enum(['none', 'rainy-library', 'quiet-spacecraft', 'turning-pages', 'greenhouse-rain', 'misty-window', 'sunday-vinyl', 'ocean-desk', 'library-lamp']),
  "rewardClaimKeys": zod.array(zod.string().min(1).max(savePracticeBodySnapshotRewardsRewardClaimKeysItemMax)).max(savePracticeBodySnapshotRewardsRewardClaimKeysMax).optional()
})
})
})

export const savePracticeResponseRevisionMin = 0;

export const savePracticeResponseSnapshotOneFocusAppsItemIdMax = 200;

export const savePracticeResponseSnapshotOneFocusAppsItemNameMax = 100;

export const savePracticeResponseSnapshotOneFocusAppsItemCategoryMax = 100;

export const savePracticeResponseSnapshotOneFocusAppsMax = 100;

export const savePracticeResponseSnapshotOneFocusSessionsItemIdMax = 200;

export const savePracticeResponseSnapshotOneFocusSessionsItemCompletedAtMax = 40;

export const savePracticeResponseSnapshotOneFocusSessionsItemDurationMinutesMax = 1440;

export const savePracticeResponseSnapshotOneFocusSessionsItemReflectionNoteMax = 2000;

export const savePracticeResponseSnapshotOneFocusSessionsMax = 20000;

export const savePracticeResponseSnapshotOneFocusOverrideEventsItemMax = 40;

export const savePracticeResponseSnapshotOneFocusOverrideEventsMax = 50000;

export const savePracticeResponseSnapshotOneFocusPendingReflectionIdOneMax = 200;

export const savePracticeResponseSnapshotOneFocusStasisTokensMin = 0;
export const savePracticeResponseSnapshotOneFocusStasisTokensMax = 100000;

export const savePracticeResponseSnapshotOneFocusProtectedDateKeysItemMax = 20;

export const savePracticeResponseSnapshotOneFocusProtectedDateKeysMax = 10000;

export const savePracticeResponseSnapshotOneRewardsLeavesMin = 0;
export const savePracticeResponseSnapshotOneRewardsLeavesMax = 10000000;

export const savePracticeResponseSnapshotOneRewardsMindfulMinutesMin = 0;
export const savePracticeResponseSnapshotOneRewardsMindfulMinutesMax = 10000000;

export const savePracticeResponseSnapshotOneRewardsUnlockedRewardsItemMax = 200;

export const savePracticeResponseSnapshotOneRewardsUnlockedRewardsMax = 1000;

export const savePracticeResponseSnapshotOneRewardsStillnessEventsItemMax = 40;

export const savePracticeResponseSnapshotOneRewardsStillnessEventsMax = 50000;

export const savePracticeResponseSnapshotOneRewardsOwnedCollectiblesMax = 4;

export const savePracticeResponseSnapshotOneRewardsRewardClaimKeysItemMax = 100;

export const savePracticeResponseSnapshotOneRewardsRewardClaimKeysMax = 10000;



export const SavePracticeResponse = zod.object({
  "revision": zod.number().int().min(savePracticeResponseRevisionMin),
  "snapshot": zod.union([zod.object({
  "version": zod.literal(1),
  "focus": zod.object({
  "apps": zod.array(zod.object({
  "id": zod.string().min(1).max(savePracticeResponseSnapshotOneFocusAppsItemIdMax),
  "name": zod.string().min(1).max(savePracticeResponseSnapshotOneFocusAppsItemNameMax),
  "category": zod.string().min(1).max(savePracticeResponseSnapshotOneFocusAppsItemCategoryMax),
  "active": zod.boolean()
})).max(savePracticeResponseSnapshotOneFocusAppsMax),
  "sessions": zod.array(zod.object({
  "id": zod.string().min(1).max(savePracticeResponseSnapshotOneFocusSessionsItemIdMax),
  "completedAt": zod.string().min(1).max(savePracticeResponseSnapshotOneFocusSessionsItemCompletedAtMax),
  "durationMinutes": zod.number().int().min(1).max(savePracticeResponseSnapshotOneFocusSessionsItemDurationMinutesMax),
  "reflection": zod.object({
  "feeling": zod.enum(['clear', 'okay', 'scattered']),
  "note": zod.string().max(savePracticeResponseSnapshotOneFocusSessionsItemReflectionNoteMax).optional()
}).optional()
})).max(savePracticeResponseSnapshotOneFocusSessionsMax),
  "overrideEvents": zod.array(zod.string().min(1).max(savePracticeResponseSnapshotOneFocusOverrideEventsItemMax)).max(savePracticeResponseSnapshotOneFocusOverrideEventsMax),
  "pendingReflectionId": zod.union([zod.string().min(1).max(savePracticeResponseSnapshotOneFocusPendingReflectionIdOneMax),zod.null()]),
  "stasisTokens": zod.number().int().min(savePracticeResponseSnapshotOneFocusStasisTokensMin).max(savePracticeResponseSnapshotOneFocusStasisTokensMax),
  "protectedDateKeys": zod.array(zod.string().min(1).max(savePracticeResponseSnapshotOneFocusProtectedDateKeysItemMax)).max(savePracticeResponseSnapshotOneFocusProtectedDateKeysMax)
}),
  "rewards": zod.object({
  "leaves": zod.number().int().min(savePracticeResponseSnapshotOneRewardsLeavesMin).max(savePracticeResponseSnapshotOneRewardsLeavesMax),
  "mindfulMinutes": zod.number().int().min(savePracticeResponseSnapshotOneRewardsMindfulMinutesMin).max(savePracticeResponseSnapshotOneRewardsMindfulMinutesMax),
  "unlockedRewards": zod.array(zod.string().min(1).max(savePracticeResponseSnapshotOneRewardsUnlockedRewardsItemMax)).max(savePracticeResponseSnapshotOneRewardsUnlockedRewardsMax),
  "equipped": zod.object({
  "breath": zod.enum(['classic', 'moonlight', 'starlight', 'sunrise', 'aurora', 'paperfold']),
  "roast": zod.enum(['classic', 'bold', 'dry', 'chaos', 'margin-notes'])
}),
  "stillnessEvents": zod.array(zod.string().min(1).max(savePracticeResponseSnapshotOneRewardsStillnessEventsItemMax)).max(savePracticeResponseSnapshotOneRewardsStillnessEventsMax),
  "ownedCollectibles": zod.array(zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page'])).max(savePracticeResponseSnapshotOneRewardsOwnedCollectiblesMax),
  "selectedCollectible": zod.union([zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page']),zod.null()]),
  "soundscape": zod.enum(['none', 'rainy-library', 'quiet-spacecraft', 'turning-pages', 'greenhouse-rain', 'misty-window', 'sunday-vinyl', 'ocean-desk', 'library-lamp']),
  "rewardClaimKeys": zod.array(zod.string().min(1).max(savePracticeResponseSnapshotOneRewardsRewardClaimKeysItemMax)).max(savePracticeResponseSnapshotOneRewardsRewardClaimKeysMax).optional()
})
}),zod.null()]),
  "updatedAt": zod.union([zod.coerce.date(),zod.null()])
})


/**
 * @summary Atomically claim an earned weekly mission or Flow Pass reward
 */
export const claimPracticeRewardBodyExpectedRevisionMin = 0;

export const claimPracticeRewardBodyClaimKeyMax = 100;

export const claimPracticeRewardBodyTimeZoneMax = 100;



export const ClaimPracticeRewardBody = zod.object({
  "expectedRevision": zod.number().int().min(claimPracticeRewardBodyExpectedRevisionMin),
  "claimKey": zod.string().min(1).max(claimPracticeRewardBodyClaimKeyMax),
  "timeZone": zod.string().min(1).max(claimPracticeRewardBodyTimeZoneMax).describe('IANA time zone used to determine the current week or month')
})

export const claimPracticeRewardResponsePracticeRevisionMin = 0;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusAppsItemIdMax = 200;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusAppsItemNameMax = 100;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusAppsItemCategoryMax = 100;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusAppsMax = 100;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemIdMax = 200;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemCompletedAtMax = 40;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemDurationMinutesMax = 1440;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemReflectionNoteMax = 2000;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsMax = 20000;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusOverrideEventsItemMax = 40;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusOverrideEventsMax = 50000;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusPendingReflectionIdOneMax = 200;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusStasisTokensMin = 0;
export const claimPracticeRewardResponsePracticeSnapshotOneFocusStasisTokensMax = 100000;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusProtectedDateKeysItemMax = 20;

export const claimPracticeRewardResponsePracticeSnapshotOneFocusProtectedDateKeysMax = 10000;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsLeavesMin = 0;
export const claimPracticeRewardResponsePracticeSnapshotOneRewardsLeavesMax = 10000000;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsMindfulMinutesMin = 0;
export const claimPracticeRewardResponsePracticeSnapshotOneRewardsMindfulMinutesMax = 10000000;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsUnlockedRewardsItemMax = 200;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsUnlockedRewardsMax = 1000;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsStillnessEventsItemMax = 40;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsStillnessEventsMax = 50000;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsOwnedCollectiblesMax = 4;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsRewardClaimKeysItemMax = 100;

export const claimPracticeRewardResponsePracticeSnapshotOneRewardsRewardClaimKeysMax = 10000;



export const ClaimPracticeRewardResponse = zod.object({
  "status": zod.enum(['claimed', 'already-claimed']),
  "practice": zod.object({
  "revision": zod.number().int().min(claimPracticeRewardResponsePracticeRevisionMin),
  "snapshot": zod.union([zod.object({
  "version": zod.literal(1),
  "focus": zod.object({
  "apps": zod.array(zod.object({
  "id": zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusAppsItemIdMax),
  "name": zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusAppsItemNameMax),
  "category": zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusAppsItemCategoryMax),
  "active": zod.boolean()
})).max(claimPracticeRewardResponsePracticeSnapshotOneFocusAppsMax),
  "sessions": zod.array(zod.object({
  "id": zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemIdMax),
  "completedAt": zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemCompletedAtMax),
  "durationMinutes": zod.number().int().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemDurationMinutesMax),
  "reflection": zod.object({
  "feeling": zod.enum(['clear', 'okay', 'scattered']),
  "note": zod.string().max(claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsItemReflectionNoteMax).optional()
}).optional()
})).max(claimPracticeRewardResponsePracticeSnapshotOneFocusSessionsMax),
  "overrideEvents": zod.array(zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusOverrideEventsItemMax)).max(claimPracticeRewardResponsePracticeSnapshotOneFocusOverrideEventsMax),
  "pendingReflectionId": zod.union([zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusPendingReflectionIdOneMax),zod.null()]),
  "stasisTokens": zod.number().int().min(claimPracticeRewardResponsePracticeSnapshotOneFocusStasisTokensMin).max(claimPracticeRewardResponsePracticeSnapshotOneFocusStasisTokensMax),
  "protectedDateKeys": zod.array(zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneFocusProtectedDateKeysItemMax)).max(claimPracticeRewardResponsePracticeSnapshotOneFocusProtectedDateKeysMax)
}),
  "rewards": zod.object({
  "leaves": zod.number().int().min(claimPracticeRewardResponsePracticeSnapshotOneRewardsLeavesMin).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsLeavesMax),
  "mindfulMinutes": zod.number().int().min(claimPracticeRewardResponsePracticeSnapshotOneRewardsMindfulMinutesMin).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsMindfulMinutesMax),
  "unlockedRewards": zod.array(zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsUnlockedRewardsItemMax)).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsUnlockedRewardsMax),
  "equipped": zod.object({
  "breath": zod.enum(['classic', 'moonlight', 'starlight', 'sunrise', 'aurora', 'paperfold']),
  "roast": zod.enum(['classic', 'bold', 'dry', 'chaos', 'margin-notes'])
}),
  "stillnessEvents": zod.array(zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsStillnessEventsItemMax)).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsStillnessEventsMax),
  "ownedCollectibles": zod.array(zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page'])).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsOwnedCollectiblesMax),
  "selectedCollectible": zod.union([zod.enum(['paper-folded-comet', 'paper-notebook-moon', 'paper-origami-rocket', 'paper-constellation-page']),zod.null()]),
  "soundscape": zod.enum(['none', 'rainy-library', 'quiet-spacecraft', 'turning-pages', 'greenhouse-rain', 'misty-window', 'sunday-vinyl', 'ocean-desk', 'library-lamp']),
  "rewardClaimKeys": zod.array(zod.string().min(1).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsRewardClaimKeysItemMax)).max(claimPracticeRewardResponsePracticeSnapshotOneRewardsRewardClaimKeysMax).optional()
})
}),zod.null()]),
  "updatedAt": zod.union([zod.coerce.date(),zod.null()])
})
})


