/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
export interface GuardedApp {
  /**
     * @minLength 1
     * @maxLength 200
     */
  id: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  name: string;
  /**
     * @minLength 1
     * @maxLength 100
     */
  category: string;
  active: boolean;
}

export type SessionReflectionFeeling = typeof SessionReflectionFeeling[keyof typeof SessionReflectionFeeling];


export const SessionReflectionFeeling = {
  clear: 'clear',
  okay: 'okay',
  scattered: 'scattered',
} as const;

export interface SessionReflection {
  feeling: SessionReflectionFeeling;
  /** @maxLength 2000 */
  note?: string;
}

export interface FocusSession {
  /**
     * @minLength 1
     * @maxLength 200
     */
  id: string;
  /**
     * @minLength 1
     * @maxLength 40
     */
  completedAt: string;
  /**
     * @minimum 1
     * @maximum 1440
     */
  durationMinutes: number;
  reflection?: SessionReflection;
}

export interface FocusSyncSnapshot {
  /** @maxItems 100 */
  apps: GuardedApp[];
  /** @maxItems 20000 */
  sessions: FocusSession[];
  /**
     * @maxItems 50000
     * @items.minLength 1
     * @items.maxLength 40
     */
  overrideEvents: string[];
  pendingReflectionId: string | null;
  /**
     * @minimum 0
     * @maximum 100000
     */
  stasisTokens: number;
  /**
     * @maxItems 10000
     * @items.minLength 1
     * @items.maxLength 20
     */
  protectedDateKeys: string[];
}

export type EquippedRewardsBreath = typeof EquippedRewardsBreath[keyof typeof EquippedRewardsBreath];


export const EquippedRewardsBreath = {
  classic: 'classic',
  moonlight: 'moonlight',
  starlight: 'starlight',
  sunrise: 'sunrise',
  aurora: 'aurora',
  paperfold: 'paperfold',
} as const;

export type EquippedRewardsRoast = typeof EquippedRewardsRoast[keyof typeof EquippedRewardsRoast];


export const EquippedRewardsRoast = {
  classic: 'classic',
  bold: 'bold',
  dry: 'dry',
  chaos: 'chaos',
  'margin-notes': 'margin-notes',
} as const;

export interface EquippedRewards {
  breath: EquippedRewardsBreath;
  roast: EquippedRewardsRoast;
}

export type RewardsSyncSnapshotOwnedCollectiblesItem = typeof RewardsSyncSnapshotOwnedCollectiblesItem[keyof typeof RewardsSyncSnapshotOwnedCollectiblesItem];


export const RewardsSyncSnapshotOwnedCollectiblesItem = {
  'paper-folded-comet': 'paper-folded-comet',
  'paper-notebook-moon': 'paper-notebook-moon',
  'paper-origami-rocket': 'paper-origami-rocket',
  'paper-constellation-page': 'paper-constellation-page',
} as const;

export type RewardsSyncSnapshotSelectedCollectible = typeof RewardsSyncSnapshotSelectedCollectible[keyof typeof RewardsSyncSnapshotSelectedCollectible] | null;


export const RewardsSyncSnapshotSelectedCollectible = {
  'paper-folded-comet': 'paper-folded-comet',
  'paper-notebook-moon': 'paper-notebook-moon',
  'paper-origami-rocket': 'paper-origami-rocket',
  'paper-constellation-page': 'paper-constellation-page',
} as const;

export type RewardsSyncSnapshotSoundscape = typeof RewardsSyncSnapshotSoundscape[keyof typeof RewardsSyncSnapshotSoundscape];


export const RewardsSyncSnapshotSoundscape = {
  none: 'none',
  'rainy-library': 'rainy-library',
  'quiet-spacecraft': 'quiet-spacecraft',
  'turning-pages': 'turning-pages',
  'greenhouse-rain': 'greenhouse-rain',
  'misty-window': 'misty-window',
  'sunday-vinyl': 'sunday-vinyl',
  'ocean-desk': 'ocean-desk',
  'library-lamp': 'library-lamp',
} as const;

export interface RewardsSyncSnapshot {
  /**
     * @minimum 0
     * @maximum 10000000
     */
  leaves: number;
  /**
     * @minimum 0
     * @maximum 10000000
     */
  mindfulMinutes: number;
  /**
     * @maxItems 1000
     * @items.minLength 1
     * @items.maxLength 200
     */
  unlockedRewards: string[];
  equipped: EquippedRewards;
  /**
     * @maxItems 50000
     * @items.minLength 1
     * @items.maxLength 40
     */
  stillnessEvents: string[];
  /** @maxItems 4 */
  ownedCollectibles: RewardsSyncSnapshotOwnedCollectiblesItem[];
  selectedCollectible: RewardsSyncSnapshotSelectedCollectible;
  soundscape: RewardsSyncSnapshotSoundscape;
  /**
     * @maxItems 10000
     * @items.minLength 1
     * @items.maxLength 100
     */
  rewardClaimKeys?: string[];
}

export interface PracticeSnapshot {
  version: 1;
  focus: FocusSyncSnapshot;
  rewards: RewardsSyncSnapshot;
}

export interface RewardClaimInput {
  /** @minimum 0 */
  expectedRevision: number;
  /**
     * @minLength 1
     * @maxLength 100
     */
  claimKey: string;
  /**
     * IANA time zone used to determine the current week or month
     * @minLength 1
     * @maxLength 100
     */
  timeZone: string;
}

export type RewardClaimResponseStatus = typeof RewardClaimResponseStatus[keyof typeof RewardClaimResponseStatus];


export const RewardClaimResponseStatus = {
  claimed: 'claimed',
  'already-claimed': 'already-claimed',
} as const;

export interface PracticeSyncResponse {
  /** @minimum 0 */
  revision: number;
  snapshot: PracticeSnapshot | null;
  updatedAt: string | null;
}

export interface RewardClaimResponse {
  status: RewardClaimResponseStatus;
  practice: PracticeSyncResponse;
}

export interface PracticeSyncRequest {
  /** @minimum 0 */
  expectedRevision: number;
  snapshot: PracticeSnapshot;
}

export interface HealthStatus {
  status: string;
}

export interface LeaderboardSync {
  /**
     * @minLength 8
     * @maxLength 128
     */
  installationId: string;
  /**
     * @minLength 2
     * @maxLength 40
     */
  nickname: string;
  /**
     * @minLength 2
     * @maxLength 120
     */
  areaKey: string;
  /**
     * @minLength 2
     * @maxLength 120
     */
  areaLabel: string;
  /**
     * @minimum 0
     * @maximum 100000
     */
  focusMinutes: number;
  /**
     * @minimum 0
     * @maximum 100000
     */
  stillnessMinutes: number;
}

export interface LeaderboardEntry {
  nickname: string;
  focusMinutes: number;
  stillnessMinutes: number;
  totalMinutes: number;
  updatedAt: string;
}

export interface AreaLeaderboard {
  areaLabel: string;
  entries: LeaderboardEntry[];
}

export interface TutorQuestion {
  /**
     * @minLength 1
     * @maxLength 80
     */
  subject: string;
  /** @maxLength 12000 */
  materials?: string;
  /**
     * Optional camera photo encoded as a data URL for visual study material.
     * @maxLength 5000000
     */
  imageDataUrl?: string;
  /**
     * @minLength 1
     * @maxLength 4000
     */
  question: string;
}

export interface TutorExplanation {
  explanation: string;
  keyIdeas: string[];
  followUp: string;
}

export type RoastRequestStyle = typeof RoastRequestStyle[keyof typeof RoastRequestStyle];


export const RoastRequestStyle = {
  classic: 'classic',
  bold: 'bold',
  dry: 'dry',
  chaos: 'chaos',
  'margin-notes': 'margin-notes',
} as const;

export type RoastRequestMode = typeof RoastRequestMode[keyof typeof RoastRequestMode];


export const RoastRequestMode = {
  override: 'override',
  'app-switch': 'app-switch',
  'end-session': 'end-session',
} as const;

export interface RoastRequest {
  style: RoastRequestStyle;
  mode: RoastRequestMode;
  /**
     * @minimum 0
     * @maximum 1440
     */
  elapsedMinutes: number;
  /**
     * @minimum 0
     * @maximum 1000
     */
  overrideCount: number;
}

export interface RoastResponse {
  roast: string;
}

export interface ApiError {
  message: string;
}

export type GetAreaLeaderboardParams = {
/**
 * @minLength 2
 * @maxLength 120
 */
areaKey: string;
};

