/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { EquippedRewardsBreath } from './equippedRewardsBreath';
import type { EquippedRewardsRoast } from './equippedRewardsRoast';

export interface EquippedRewards {
  breath: EquippedRewardsBreath;
  roast: EquippedRewardsRoast;
}
