/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type EquippedRewardsBreath = typeof EquippedRewardsBreath[keyof typeof EquippedRewardsBreath];


export const EquippedRewardsBreath = {
  classic: 'classic',
  moonlight: 'moonlight',
  starlight: 'starlight',
  sunrise: 'sunrise',
  aurora: 'aurora',
  paperfold: 'paperfold',
} as const;
