/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { SessionReflection } from './sessionReflection';

export interface FocusSession {
  /**
     * @minLength 1
     * @maxLength 200
     */
  id: string;
  /**
     * @minLength 1
     * @maxLength 40
     */
  completedAt: string;
  /**
     * @minimum 1
     * @maximum 1440
     */
  durationMinutes: number;
  reflection?: SessionReflection;
}
