/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { FocusSession } from './focusSession';
import type { GuardedApp } from './guardedApp';

export interface FocusSyncSnapshot {
  /** @maxItems 100 */
  apps: GuardedApp[];
  /** @maxItems 20000 */
  sessions: FocusSession[];
  /**
     * @maxItems 50000
     * @items.minLength 1
     * @items.maxLength 40
     */
  overrideEvents: string[];
  pendingReflectionId: string | null;
  /**
     * @minimum 0
     * @maximum 100000
     */
  stasisTokens: number;
  /**
     * @maxItems 10000
     * @items.minLength 1
     * @items.maxLength 20
     */
  protectedDateKeys: string[];
}
