/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type GetAreaLeaderboardParams = {
/**
 * @minLength 2
 * @maxLength 120
 */
areaKey: string;
};
