/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface LeaderboardSync {
  /**
     * @minLength 8
     * @maxLength 128
     */
  installationId: string;
  /**
     * @minLength 2
     * @maxLength 40
     */
  nickname: string;
  /**
     * @minLength 2
     * @maxLength 120
     */
  areaKey: string;
  /**
     * @minLength 2
     * @maxLength 120
     */
  areaLabel: string;
  /**
     * @minimum 0
     * @maximum 100000
     */
  focusMinutes: number;
  /**
     * @minimum 0
     * @maximum 100000
     */
  stillnessMinutes: number;
}
