/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PracticeSnapshot } from './practiceSnapshot';

export interface PracticeSyncResponse {
  /** @minimum 0 */
  revision: number;
  snapshot: PracticeSnapshot | null;
  updatedAt: Date | null;
}
