/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { FocusSyncSnapshot } from './focusSyncSnapshot';
import type { RewardsSyncSnapshot } from './rewardsSyncSnapshot';

export interface PracticeSnapshot {
  version: 1;
  focus: FocusSyncSnapshot;
  rewards: RewardsSyncSnapshot;
}
