/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type RewardsSyncSnapshotSelectedCollectible = typeof RewardsSyncSnapshotSelectedCollectible[keyof typeof RewardsSyncSnapshotSelectedCollectible] | null;


export const RewardsSyncSnapshotSelectedCollectible = {
  'paper-folded-comet': 'paper-folded-comet',
  'paper-notebook-moon': 'paper-notebook-moon',
  'paper-origami-rocket': 'paper-origami-rocket',
  'paper-constellation-page': 'paper-constellation-page',
} as const;
