/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type RewardClaimResponseStatus = typeof RewardClaimResponseStatus[keyof typeof RewardClaimResponseStatus];


export const RewardClaimResponseStatus = {
  claimed: 'claimed',
  'already-claimed': 'already-claimed',
} as const;
