/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { PracticeSyncResponse } from './practiceSyncResponse';
import type { RewardClaimResponseStatus } from './rewardClaimResponseStatus';

export interface RewardClaimResponse {
  status: RewardClaimResponseStatus;
  practice: PracticeSyncResponse;
}
