/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface RewardClaimInput {
  /** @minimum 0 */
  expectedRevision: number;
  /**
     * @minLength 1
     * @maxLength 100
     */
  claimKey: string;
  /**
     * IANA time zone used to determine the current week or month
     * @minLength 1
     * @maxLength 100
     */
  timeZone: string;
}
