/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { EquippedRewards } from './equippedRewards';
import type { RewardsSyncSnapshotOwnedCollectiblesItem } from './rewardsSyncSnapshotOwnedCollectiblesItem';
import type { RewardsSyncSnapshotSelectedCollectible } from './rewardsSyncSnapshotSelectedCollectible';
import type { RewardsSyncSnapshotSoundscape } from './rewardsSyncSnapshotSoundscape';

export interface RewardsSyncSnapshot {
  /**
     * @minimum 0
     * @maximum 10000000
     */
  leaves: number;
  /**
     * @minimum 0
     * @maximum 10000000
     */
  mindfulMinutes: number;
  /**
     * @maxItems 1000
     * @items.minLength 1
     * @items.maxLength 200
     */
  unlockedRewards: string[];
  equipped: EquippedRewards;
  /**
     * @maxItems 50000
     * @items.minLength 1
     * @items.maxLength 40
     */
  stillnessEvents: string[];
  /** @maxItems 4 */
  ownedCollectibles: RewardsSyncSnapshotOwnedCollectiblesItem[];
  selectedCollectible: RewardsSyncSnapshotSelectedCollectible;
  soundscape: RewardsSyncSnapshotSoundscape;
  /**
     * @maxItems 10000
     * @items.minLength 1
     * @items.maxLength 100
     */
  rewardClaimKeys?: string[];
}
