/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type RewardsSyncSnapshotSoundscape = typeof RewardsSyncSnapshotSoundscape[keyof typeof RewardsSyncSnapshotSoundscape];


export const RewardsSyncSnapshotSoundscape = {
  none: 'none',
  'rainy-library': 'rainy-library',
  'quiet-spacecraft': 'quiet-spacecraft',
  'turning-pages': 'turning-pages',
  'greenhouse-rain': 'greenhouse-rain',
  'misty-window': 'misty-window',
  'sunday-vinyl': 'sunday-vinyl',
  'ocean-desk': 'ocean-desk',
  'library-lamp': 'library-lamp',
} as const;
