/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { RoastRequestMode } from './roastRequestMode';
import type { RoastRequestStyle } from './roastRequestStyle';

export interface RoastRequest {
  style: RoastRequestStyle;
  mode: RoastRequestMode;
  /**
     * @minimum 0
     * @maximum 1440
     */
  elapsedMinutes: number;
  /**
     * @minimum 0
     * @maximum 1000
     */
  overrideCount: number;
}
