/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type RoastRequestStyle = typeof RoastRequestStyle[keyof typeof RoastRequestStyle];


export const RoastRequestStyle = {
  classic: 'classic',
  bold: 'bold',
  dry: 'dry',
  chaos: 'chaos',
  'margin-notes': 'margin-notes',
} as const;
