/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export type RoastRequestMode = typeof RoastRequestMode[keyof typeof RoastRequestMode];


export const RoastRequestMode = {
  override: 'override',
  'app-switch': 'app-switch',
  'end-session': 'end-session',
} as const;
