/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */
import type { SessionReflectionFeeling } from './sessionReflectionFeeling';

export interface SessionReflection {
  feeling: SessionReflectionFeeling;
  /** @maxLength 2000 */
  note?: string;
}
