/**
 * Generated by orval v8.23.0 🍺
 * Do not edit manually.
 * Api
 * API specification
 * OpenAPI spec version: 0.1.0
 */

export interface TutorQuestion {
  /**
     * @minLength 1
     * @maxLength 80
     */
  subject: string;
  /** @maxLength 12000 */
  materials?: string;
  /**
     * Optional camera photo encoded as a data URL for visual study material.
     * @maxLength 5000000
     */
  imageDataUrl?: string;
  /**
     * @minLength 1
     * @maxLength 4000
     */
  question: string;
}
